### ISSUE TITLE
Add iso_country_code to Team model

### ISSUE THREAD

**Issue by panatale1** [panatale1/gb_directory#2]
Invites went out to US, Canada, and Mexico based teams, we'll need to add iso_country_code (2 letters) to the Team model

**Comment by panatale1** [comment]
This field can be based on the state_province field on the Team model. Updates to models require a migration to be created and committed. Information on migrations can be found [here](https://docs.djangoproject.com/en/4.1/ref/django-admin/#django-admin-makemigrations).

The above link should be taken with a grain of salt when working in our project. since we're using poetry, the proper way to make migrations in our database should be `poetry run ./manage.py makemigrations`. Then you'll want to apply the migrations to your database, details of which are in the README for the repo

**Comment by souzamartin** [comment]
Updated the model and successfully created and ran the migration (I think), but unable to push local changes because branch is protected. I believe @panatale1 can change the branch protection settings.

**Comment by panatale1** [comment]
@souzamartin did you create a branch to work on to push instead of working on the master branch?

**Comment by souzamartin** [comment]
@panatale1 I did. It's the one GitHub conveniently associated with this issue for us.

**Comment by panatale1** [comment]
okay, i probably just effed up my branch protection, it's really the first time i'm setting it up. you should be okay to push and do a pull request now

**Comment by panatale1** [comment]
Looks good, @souzamartin! i approved your PR and merged your branch into main already
